const fs = require("fs");

const questionsAnswersDataPath = "./QuestionsAnswersData.json"


/*
The following function is to post a new question.
we create a new json object with question as key  and body being
<questiondId> :       {
                       "QuestionPosted":
                                {
                                    "userName" : userName,
                                    "content" : questionContent
                                },
                       "AnswersPosted":   []
                    }
The answeres posted list is initially empty.
Input Parameters:
questionid - the unique id which is generated by server
userName - The username of the user(Email) 
questionContent - the content of the question
Returns:
Success- if question is posted successfully
Failure - if the server is having trouble with JSON file

*/

const postQuestion = (questionId,userName,questionContent) =>
{
    try
    {
        const Data = fs.readFileSync(questionsAnswersDataPath)
  
        // we create a JSON object by parsing the file  
        questionsAnswersData= JSON.parse( Data );
        // creating a new json object for the question
        // empyt array of answers for this question
        questionsAnswersData[String(questionId)] =
        {
            "QuestionPosted":
                                {
                                    "userName" : userName,
                                    "content" : questionContent
                                },
            "AnswersPosted":   []
        }
        try
        {   // we can post the question
            fs.writeFileSync(questionsAnswersDataPath, JSON.stringify(questionsAnswersData,null, 2));
            return "Success";
        }
        catch(err)
        {
            console.log("The Server is having trouble with JSON file", err);
            return "Failure";
        }

    }
    catch(err)
    {
        console.log("The Server is having trouble with JSON file", err);
        return "Failure";
    }
}


const listAllQnA = () =>
{
    try
    {
        const Data = fs.readFileSync(questionsAnswersDataPath);
        questionsAnswersData = JSON.parse( Data );
        //console.log(questionsAnswersData);
        const dataString = JSON.stringify(questionsAnswersData);
        return dataString;

    }
    catch(err)
    {
        console.log("The Server is having trouble with JSON file", err);
        return "ServerIssue";
    }

}

module.exports = {postQuestion,listAllQnA};


      

